"project_id" : "2"
"base_path" : "."
"base_url" : "https://berty.crowdin.com"

"commit_message": 'fix(i18n): new %language% translations


Signed-off-by: Berty Assistant <22729528+berty-assistant@users.noreply.github.com>
'

"append_commit_message": false
"preserve_hierarchy": true

files: [
  {
  "source" : "/js/packages/i18n/locale/en-US/messages.json",
  "translation" : "/js/packages/i18n/locale/%locale%/%original_file_name%",
  },
  {
  "source" : "/go/localization/locales/en-US/localization.json",
  "translation" : "/go/localization/locales/%locale%/%original_file_name%",
  },
  {
   "source" : "/js/ios/Localization/Base.lproj/Localizable.strings",
   "translation" : "/js/ios/Localization/%osx_code%/%original_file_name%",
  },
]
