rdvp:
    - name: test rdvp
      amount: 1
      groups:
      connections:
          - name: connection
            to: internet
            protocol: tcp

peer:
    - name: test peers 1
      amount: 8
      connections:
        - name: connection 1
          to: internet
          protocol: tcp

#relay:
#    - name: test relay
#      amount: 1
#      groups:
#      connections:
#          - name: connection
#            to: internet
#            protocol: tcp
