rdvp:
    - name: test rdvp
      amount: 2
      connections:
          - name: connection
            to: internet
            protocol: tcp

peer:
    - name: test peers 1
      amount: 5
      groups:
      - name: message group
        tests:
        - type: text
          size: 40KB
          interval: 10
      connections:
        - name: connection
          to: internet
          protocol: tcp
      routers:
        - type: rdvp
          address: test rdvp
        - type: relay
          address: test relay

relay:
    - name: test relay
      amount: 2
      groups:
      connections:
          - name: connection
            to: internet
            protocol: tcp
