rdvp:
    - name: test rdvp
      amount: 1
      connections:
          - name: connection
            to: internet
            protocol: tcp

peer:
    - name: test peers 1
      amount: 2
      groups:
      - name: message group
        tests:
        - type: text
          size: 40KB
          interval: 10
      connections:
        - name: connection
          to: internet
          protocol: tcp
      routers:
        - type: rdvp
          address: test rdvp

#relay:
#    - name: test relay
#      amount: 1
#      groups:
#      connections:
#          - name: connection
#            to: internet
#            protocol: tcp
