#rdvp:
#    - name: test rdvp
#      amount: 1
#      connections:
#          - name: connection
#            to: internet
#            protocol: tcp
#          - name: thing
#            to: lan
#            protocol: udp
#
peer:
    - name: test peers 1
      amount: 2
      daemon:
      - name: message group
        tests:
        - type: text
          size: 3KB
          interval: 2
          amount: 25
        - type: media
          size: 15KB
          interval: 3
          amount: 25
      connections:
        - name: connection
          to: internet
          protocol: tcp
#      routers:
#        - type: rdvp
#          address: test rdvp
#        - type: relay
#          address: test relay

#replication:
#    - name: repl1
#      amount: 2
#      groups:
#      - name: message group
#      connections:
#          - name: connection
#            to: internet
#            protocol: tcp
#          - name: thing
#            to: lan
#            protocol: udp
#
#relay:
#    - name: test relay
#      amount: 2
#      connections:
#          - name: connection
#            to: internet
#            protocol: tcp
##
#bootstrap:
#    - name: test bs
#      amount: 2
#      connections:
#          - name: connection
#            to: internet
#            protocol: tcp
#      routers:
#          - type: rdvp
#            address: test rdvp
#          - type: relay
#            address: test relay
